### ISSUE TITLE
KeyError in Preprocessing Code

### ISSUE THREAD

**Issue by ClaraLHibbs** [yafi38/scGIST#11]
I am new to scRNA data and python.

I'm currently experimenting with scGIST with the hope of using it in the near future on my own scRNA data. I'm using the TS_Lung.h5ad data from Tabula Sapiens that was used in the paper.

I am getting stuck near the end of the preprocessing code, however.

Here is the code:
```python

# keep only cell types with more than 500 cells
counts = pd.DataFrame(adata.obs['CellType'].value_counts())
cell_types_to_keep = list(counts[counts['CellType'] > 500].index)
adata = adata[adata.obs['CellType'].isin(cell_types_to_keep),:]

# filter to 1000 cells per class
target_cells = 1000
cluster_key = 'CellType'
adata = [adata[adata.obs[cluster_key].isin([clust])] for clust in adata.obs[cluster_key].cat.categories]
for dat in adata:
	if dat.n_obs > target_cells:
		sc.pp.subsample(dat, n_obs=target_cells)
adata = adata[0].concatenate(*adata[1:])

``` 

And here is the error:

```python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'CellType'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/clarahibbs/Desktop/Hayes_Rotation/scGIST_trial/scGIST-trial.py", line 54, in <module>
    counts = pd.DataFrame(adata.obs['CellType'].value_counts())
                          ~~~~~~~~~^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'CellType'
``` 

I would appreciate any help as searching the internet isn't doing much for me!

**Comment by yafi38** [comment]
Hello @ch1bbs1 
Here `CellType` represents the column where your cell types are present. The name of the column may be different for your dataset. You can try to browse your dataset and find it out.
Let me know if you are unable to find it.
Thanks.

**Comment by ClaraLHibbs** [comment]
Hi!
I've been unable to figure out what the column name is for the TS_Lung.h5ad dataset. I've tried creating a SeuratObject to better read the file, but I've been unable to get that to work.
If you happen to know the column name from when using the dataset for the scGIST paper, I would greatly appreciate the help!
Thanks.

**Comment by yafi38** [comment]
Hello @ch1bbs1.

In our dataset, the cell types were in the 'celltype' column/observation. You could find the cell type names in the datasets that we used in the [create_panels.py](https://github.com/yafi38/scGIST/blob/9b92fa1498964a05a096b9b35054fb92cdfad9e1/benchmarks/create_panels.py) file.

Let us know if it helps with your problem. Thanks.

**Comment by ClaraLHibbs** [comment]
Hi!

I'm still getting a Key Error no matter what I try for the column label.
I've converted my own data from a SeuratObject to h5ad where I 100% know the column label, but I'm still getting a Key Error.

Do you have ideas on what could be wrong? Thanks.

**Comment by yafi38** [comment]
Hi @ch1bbs1.

You can try printing the `adata.obs` and see what `obs` you have. One of them should be the one which has cell types.

**Comment by yafi38** [comment]
Closing due to inactivity.
